name: Setup Development Environment

on:
  workflow_dispatch:
  push:
    paths:
      - .github/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/copilot-setup-steps.yml

permissions:
  contents: read

jobs:
  # The job name MUST be 'copilot-setup-steps' to be picked up by GitHub Copilot
  copilot-setup-steps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore src/OctoshiftCLI.sln

      - name: Format code
        run: dotnet format src/OctoshiftCLI.sln --verify-no-changes

      - name: Build
        run: dotnet build src/OctoshiftCLI.sln --no-restore
